language: node_js
os:
  - linux
node_js:
  - node
script:
  - npm install
  - npm run lint
  - npm run build
deploy:
  - provider: script
    skip_cleanup: true # do not delete the built assets
    script: sh $TRAVIS_BUILD_DIR/.travis-deploy.sh
    on:
      branch: master
